version: 2.1
# Definition of the pipeline jobs
jobs:
  # Build node project
  build:
    # Using CircleCi DOcker image for Node.js
    docker:
      - image: circleci/node:latest
        # Setting dockerhub auth configs to deploy to our dockerhub
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      # Checkout (Clone the repository to circleci on every commit) the repository
      - checkout

      #new
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          # Command name
          name: Install dependencies
          # Command code
          command: yarn install
      - run:
          name: Run automated tests
          command: yarn test
      
            #new
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/food-demo:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD docker.io
            docker push $DOCKERHUB_USERNAME/food-demo:latest

# Define workflows. Like a small orchestration on how the jobs will be executed
workflows:
  version: 2
  food-demo-build: 
    jobs:
      - build: 
          context: food_demo
          # Filter to trigger the workflow
          filters:
            # Specify the branches filters
            branches:
              # Will execute only on changes on these two branches
              only:
                - main
                - ci-cd

# version: 2.1
# orbs:
#   node: circleci/node@5
# jobs:
#   food_demo_test_node:
#     # Build node project
#     # executor: node/default
#     docker:
#       - image: cimg/node:19.8.1
#       # - image: cimg/base:stable
#     steps:
#       - checkout
#       - run:
#           name: npm update
#           command: sudo npm install -g yarn@latest
#       - run:
#           name: run automated tests
#           command: yarn test

#   # food_demo_build_node:
#   #   # Build node project
#   #   executor: node/default
#   #   steps:
#   #     - checkout
#   #     - node/install-packages:
#   #         pkg-manager: yarn
#   #     - run:
#   #         name: run automated build
#   #         command: yarn build

#   # food_demo_deployment_node:
#   #   # Using the docker image of node js to deploy on docker
#   #   docker:
#   #     - image: cimg/node:19.8.1
#   #   steps:
#   #     # Checkout (Clone the repository to circleci on every commit) the repository
#   #     - checkout
#   #     - run:
#   #         # Name of the step
#   #         name: npm update
#   #         # Install the latest version of npm
#   #         command: sudo npm install -g npm@lastest
#   #     - run:
#   #         name: run automated tests
#   #         command: npm test

# workflows:
#   food_demo:
#     jobs:
#       - food_demo_test_node
#       # - food_demo_build_node
#       # - food_demo_deployment_node