version: 2.1
# Definition of the pipeline jobs
jobs:
  # Build node project
  build:
    # Using CircleCi DOcker image for Node.js
    docker:
      - image: cimg/node:18.10.0
        # Setting dockerhub auth configs to deploy to our dockerhub
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      # Checkout (Clone the repository to circleci on every commit) the repository
      - checkout

      # Helps to run docker commands in the executor
      - setup_remote_docker:
          # Caches the DockerFile in the job to rebuilt from the previous builds if no changes in the Dockerfile
          # This minimizes the time to build the image
          docker_layer_caching: true

      # - run:
      #     # Command name
      #     name: Install node version 16.14.0
      #     # Command code
      #     command: nvm install 16.14.0

      # - run:
      #     # Command name
      #     name: Switch to the installed nodejs version
      #     # Command code
      #     command: nvm use 16.14.0      
      
      - run:
          # Command name
          name: Install the test dependencies
          # Command code
          command: yarn add jest ts-jest @types/jest -D
      - run:
          name: Run automated tests
          command: yarn test

      # Conditions
      - when:
          # Push the image from the main branch when all pull requests are accepted
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            # Builds the docker image and deploys it on dockerhub
            - run:
                name: Build and Push Docker Image
                command: |
                  docker build -t $DOCKERHUB_USERNAME/food-demo:latest .
                  docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD docker.io
                  docker push $DOCKERHUB_USERNAME/food-demo:latest

# Define workflows. Like a small orchestration on how the jobs will be executed
workflows:
  version: 2
  food-demo-build:
    jobs:
      - build:
          context: food_demo
          # Filter to trigger the workflow
          filters:
            # Specify the branches filters
            branches:
              # Will execute only on changes on these two branches
              only:
                - main
                - ci-cd
